In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from tensorflow.keras.models import load_model
import tensorflow as tf

In [36]:
## load the trained model,scaler pickle, onehot
model=load_model('model.h5')
with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)
# with open('model.h5', 'rb') as file:
#     model = load_model(file)
# onehot_encoder_geo=pickle.load(open('onehot_encoder_geo.pkl','rb'))

WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [26]:
input_data={
    'CreditScore':600,
    'Geography': 'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000

}

In [27]:
geo_trans=onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
# gender_trans=label_encoder_gender.transform([[input_data['Gender']]])
# geo_trans,gender_trans
geo_encoded_df=pd.DataFrame(geo_trans,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

d:\udemy\DL\ANN\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [28]:
input_data=pd.DataFrame([input_data])

In [29]:
input_df=pd.concat([input_data.reset_index(drop=True), geo_encoded_df],axis=1)

In [30]:
input_df.drop('Geography',axis=1,inplace=True)

In [31]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [33]:
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [37]:
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 357ms/step

array([[0.0063058]], dtype=float32)

In [38]:
prediction_prob=prediction[0][0]

In [39]:
if prediction_prob>0.5:
    print(f"The customer is likely to leave the bank with a probability of {prediction_prob:.2f}")
else:
    print(f"The customer is likely to stay with the bank with a probability of {1-prediction_prob:.2f}")

The customer is likely to stay with the bank with a probability of 0.99