In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [13]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [14]:
data.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [15]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [16]:
one_hot_encoder_geo=OneHotEncoder()
geo_encoded=one_hot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))

In [17]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [18]:
data=pd.concat([data.drop(['Geography'],axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [19]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [20]:
## split the data into training and testing set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## feature scaling
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [21]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Regression Problem Statement

In [ ]:
# !pip install tensorflow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Requirement already satisfied: tensorflow in .\venv\Lib\site-packages (2.15.0)
Requirement already satisfied: tensorflow-intel==2.15.0 in .\venv\Lib\site-packages (from tensorflow) (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.16.0)
Requirement already satisfied: libclang>=13.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.26.4)
Requirement already satisfied: opt-einsum>=2.3.2 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.4.0)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.25.9)
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (69.5.1)
Requirement already satisfied: six>=1.12.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.15.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.14.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.31.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.81.0)
Requirement already satisfied: tensorboard<2.16,>=2.15 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.53.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (1.4.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.10.2)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.34.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.1.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (48.0.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in .\venv\Lib\site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2026.5.20)
Requirement already satisfied: wheel<1.0,>=0.23.0 in .\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.15.0->tensorflow) (0.46.3)
Requirement already satisfied: cffi>=2.0.0 in .\venv\Lib\site-packages (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.0.0)
Requirement already satisfied: pycparser in .\venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in .\venv\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.6.3)
Requirement already satisfied: oauthlib>=3.0.0 in .\venv\Lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.3.1)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.0.3)

In [25]:
model=Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
        Dense(32,activation='relu'),
        Dense(1) ## output layer for binary classification
    ]
)
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                832

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [28]:
## Setup the tensorboard
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [29]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [30]:
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[tensorboard_callback,early_stopping_callback])

Epoch 1/100
WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 4ms/step - loss: 100369.0078 - mae: 100369.0078 - val_loss: 98488.6094 - val_mae: 98488.6094
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 99548.9219 - mae: 99548.9219 - val_loss: 96843.1094 - val_mae: 96843.1094
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 96713.3438 - mae: 96713.3438 - val_loss: 92691.0000 - val_mae: 92691.0000
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 91156.8594 - mae: 91156.8594 - val_loss: 85810.3281 - val_mae: 85810.3281
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 83103.5469 - mae: 83103.5469 - val_loss: 77033.7266 - val_mae: 77033.7266
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 73791.6562 - mae: 73791.6562 - val_loss: 68151.7656 - val_mae: 68151.7656
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 64910.2344 - mae: 64910.2344 - val_loss: 60573.3789 - val_mae: 60573.3789
Epoch 8/100
250/250 [==============================] - 2s 6ms/step - loss: 57962.2031 - mae: 57962.2031 - val_loss: 55254.7188 - val_mae: 55254.7188
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 53619.2773 - mae: 53619.2773 - val_loss: 52512.0742 - val_mae: 52512.0742
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 51477.3750 - mae: 51477.3750 - val_loss: 51430.2969 - val_mae: 51430.2969
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 50611.5938 - mae: 50611.5938 - val_loss: 51061.2656 - val_mae: 51061.2656
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 50299.5039 - mae: 50299.5039 - val_loss: 50941.3008 - val_mae: 50941.3008
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 50168.9570 - mae: 50168.9570 - val_loss: 50865.3867 - val_mae: 50865.3867
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 50099.2852 - mae: 50099.2852 - val_loss: 50813.1680 - val_mae: 50813.1680
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 50043.5273 - mae: 50043.5273 - val_loss: 50759.7031 - val_mae: 50759.7031
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50000.9961 - mae: 50000.9961 - val_loss: 50717.6484 - val_mae: 50717.6484
Epoch 17/100
250/250 [==============================] - 1s 5ms/step - loss: 49960.7188 - mae: 49960.7188 - val_loss: 50674.5117 - val_mae: 50674.5117
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 49929.7539 - mae: 49929.7539 - val_loss: 50643.1250 - val_mae: 50643.1250
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 49898.3906 - mae: 49898.3906 - val_loss: 50614.4570 - val_mae: 50614.4570
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49869.2461 - mae: 49869.2461 - val_loss: 50591.6680 - val_mae: 50591.6680
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 49842.0977 - mae: 49842.0977 - val_loss: 50566.2070 - val_mae: 50566.2070
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49818.9453 - mae: 49818.9453 - val_loss: 50547.2031 - val_mae: 50547.2031
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49798.2305 - mae: 49798.2305 - val_loss: 50531.6211 - val_mae: 50531.6211
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49777.1641 - mae: 49777.1641 - val_loss: 50508.7969 - val_mae: 50508.7969
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 49757.6250 - mae: 49757.6250 - val_loss: 50492.2422 - val_mae: 50492.2422
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49741.0078 - mae: 49741.0078 - val_loss: 50480.0586 - val_mae: 50480.0586
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49726.2188 - mae: 49726.2188 - val_loss: 50456.7148 - val_mae: 50456.7148
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49705.9727 - mae: 49705.9727 - val_loss: 50446.9648 - val_mae: 50446.9648
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49694.7461 - mae: 49694.7461 - val_loss: 50440.6289 - val_mae: 50440.6289
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49679.9297 - mae: 49679.9297 - val_loss: 50428.2852 - val_mae: 50428.2852
Epoch 31/100
250/250 [==============================] - 1s 4ms/step - loss: 49663.1992 - mae: 49663.1992 - val_loss: 50420.3984 - val_mae: 50420.3984
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49650.0312 - mae: 49650.0312 - val_loss: 50412.1641 - val_mae: 50412.1641
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49637.3516 - mae: 49637.3516 - val_loss: 50409.9023 - val_mae: 50409.9023
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49624.7656 - mae: 49624.7656 - val_loss: 50389.6641 - val_mae: 50389.6641
Epoch 35/100
250/250 [==============================] - 1s 4ms/step - loss: 49613.0352 - mae: 49613.0352 - val_loss: 50384.8164 - val_mae: 50384.8164
Epoch 36/100
250/250 [==============================] - 1s 5ms/step - loss: 49603.4609 - mae: 49603.4609 - val_loss: 50384.2656 - val_mae: 50384.2656
Epoch 37/100
250/250 [==============================] - 1s 4ms/step - loss: 49586.1445 - mae: 49586.1445 - val_loss: 50378.6211 - val_mae: 50378.6211
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49579.9141 - mae: 49579.9141 - val_loss: 50371.2266 - val_mae: 50371.2266
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 49568.6406 - mae: 49568.6406 - val_loss: 50372.7969 - val_mae: 50372.7969
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49558.0195 - mae: 49558.0195 - val_loss: 50376.1016 - val_mae: 50376.1016
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49548.5664 - mae: 49548.5664 - val_loss: 50373.6250 - val_mae: 50373.6250
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49545.3242 - mae: 49545.3242 - val_loss: 50368.0039 - val_mae: 50368.0039
Epoch 43/100
250/250 [==============================] - 1s 4ms/step - loss: 49533.3750 - mae: 49533.3750 - val_loss: 50368.2773 - val_mae: 50368.2773
Epoch 44/100
250/250 [==============================] - 1s 4ms/step - loss: 49524.3125 - mae: 49524.3125 - val_loss: 50374.3906 - val_mae: 50374.3906
Epoch 45/100
250/250 [==============================] - 1s 4ms/step - loss: 49514.7656 - mae: 49514.7656 - val_loss: 50365.6016 - val_mae: 50365.6016
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49509.9922 - mae: 49509.9922 - val_loss: 50362.6523 - val_mae: 50362.6523
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 49500.5000 - mae: 49500.5000 - val_loss: 50359.1836 - val_mae: 50359.1836
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49493.0977 - mae: 49493.0977 - val_loss: 50359.0195 - val_mae: 50359.0195
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 49486.8672 - mae: 49486.8672 - val_loss: 50356.4531 - val_mae: 50356.4531
Epoch 50/100
250/250 [==============================] - 1s 4ms/step - loss: 49480.5195 - mae: 49480.5195 - val_loss: 50354.3867 - val_mae: 50354.3867
Epoch 51/100
250/250 [==============================] - 1s 4ms/step - loss: 49475.3516 - mae: 49475.3516 - val_loss: 50356.1758 - val_mae: 50356.1758
Epoch 52/100
250/250 [==============================] - 2s 6ms/step - loss: 49469.0938 - mae: 49469.0938 - val_loss: 50351.1211 - val_mae: 50351.1211
Epoch 53/100
250/250 [==============================] - 1s 5ms/step - loss: 49461.6680 - mae: 49461.6680 - val_loss: 50343.4727 - val_mae: 50343.4727
Epoch 54/100
250/250 [==============================] - 1s 4ms/step - loss: 49456.1680 - mae: 49456.1680 - val_loss: 50350.8438 - val_mae: 50350.8438
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49448.7578 - mae: 49448.7578 - val_loss: 50346.7383 - val_mae: 50346.7383
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49444.7031 - mae: 49444.7031 - val_loss: 50350.1328 - val_mae: 50350.1328
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49443.0938 - mae: 49443.0938 - val_loss: 50353.5273 - val_mae: 50353.5273
Epoch 58/100
250/250 [==============================] - 1s 4ms/step - loss: 49432.9062 - mae: 49432.9062 - val_loss: 50349.5312 - val_mae: 50349.5312

In [32]:
%load_ext tensorboard

In [35]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 4148), started 0:06:58 ago. (Use '!kill 4148' to kill it.)

In [36]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 [==============================] - 1s 3ms/step - loss: 50343.4727 - mae: 50343.4727
Test Loss: 50343.47265625, Test MAE: 50343.47265625

In [37]:
model.save('regression_model.h5')

d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(