In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [4]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [5]:
one_hot_encoder_geo=OneHotEncoder()
geo_encoded=one_hot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))

In [6]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
data=pd.concat([data.drop(['Geography'],axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [9]:
## split the data into training and testing set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## feature scaling
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
with open('label_encoder_gender_reg.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder_geo_reg.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)
with open('scaler_reg.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Regression Problem Statement

In [12]:
# !pip install tensorflow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [13]:
model=Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
        Dense(32,activation='relu'),
        Dense(1) ## output layer for binary classification
    ]
)
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [15]:
## Setup the tensorboard
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [16]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [17]:
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[tensorboard_callback,early_stopping_callback])

Epoch 1/100
WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 6s 18ms/step - loss: 100391.1719 - mae: 100391.1719 - val_loss: 98561.3750 - val_mae: 98561.3750
Epoch 2/100
250/250 [==============================] - 3s 13ms/step - loss: 99749.6719 - mae: 99749.6719 - val_loss: 97216.5312 - val_mae: 97216.5312
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 97378.2500 - mae: 97378.2500 - val_loss: 93689.8594 - val_mae: 93689.8594
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 92640.4531 - mae: 92640.4531 - val_loss: 87733.3047 - val_mae: 87733.3047
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 85591.7891 - mae: 85591.7891 - val_loss: 79841.3203 - val_mae: 79841.3203
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 77039.0078 - mae: 77039.0078 - val_loss: 71260.4141 - val_mae: 71260.4141
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 68375.5234 - mae: 68375.5234 - val_loss: 63382.6562 - val_mae: 63382.6562
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 60975.9844 - mae: 60975.9844 - val_loss: 57386.5430 - val_mae: 57386.5430
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 55760.7070 - mae: 55760.7070 - val_loss: 53618.9805 - val_mae: 53618.9805
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 52630.7891 - mae: 52630.7891 - val_loss: 51801.3945 - val_mae: 51801.3945
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 51186.8242 - mae: 51186.8242 - val_loss: 51125.4297 - val_mae: 51125.4297
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 50579.2148 - mae: 50579.2148 - val_loss: 50882.1328 - val_mae: 50882.1328
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 50333.1953 - mae: 50333.1953 - val_loss: 50795.5078 - val_mae: 50795.5078
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50208.8398 - mae: 50208.8398 - val_loss: 50743.3438 - val_mae: 50743.3438
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 50134.5352 - mae: 50134.5352 - val_loss: 50705.2266 - val_mae: 50705.2266
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 50078.0664 - mae: 50078.0664 - val_loss: 50663.4102 - val_mae: 50663.4102
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 50031.4297 - mae: 50031.4297 - val_loss: 50622.7969 - val_mae: 50622.7969
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 49995.7891 - mae: 49995.7891 - val_loss: 50586.3359 - val_mae: 50586.3359
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 49954.8164 - mae: 49954.8164 - val_loss: 50548.8047 - val_mae: 50548.8047
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49929.7109 - mae: 49929.7109 - val_loss: 50518.1094 - val_mae: 50518.1094
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49894.0312 - mae: 49894.0312 - val_loss: 50495.6875 - val_mae: 50495.6875
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 49869.2305 - mae: 49869.2305 - val_loss: 50470.6836 - val_mae: 50470.6836
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49845.4727 - mae: 49845.4727 - val_loss: 50443.2656 - val_mae: 50443.2656
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49819.9414 - mae: 49819.9414 - val_loss: 50427.7539 - val_mae: 50427.7539
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49798.6914 - mae: 49798.6914 - val_loss: 50403.3984 - val_mae: 50403.3984
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49780.3203 - mae: 49780.3203 - val_loss: 50389.7266 - val_mae: 50389.7266
Epoch 27/100
250/250 [==============================] - 1s 4ms/step - loss: 49764.5703 - mae: 49764.5703 - val_loss: 50369.8945 - val_mae: 50369.8945
Epoch 28/100
250/250 [==============================] - 1s 4ms/step - loss: 49743.9844 - mae: 49743.9844 - val_loss: 50356.5156 - val_mae: 50356.5156
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49729.6602 - mae: 49729.6602 - val_loss: 50338.3750 - val_mae: 50338.3750
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49710.7148 - mae: 49710.7148 - val_loss: 50329.4609 - val_mae: 50329.4609
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49697.9609 - mae: 49697.9609 - val_loss: 50325.2773 - val_mae: 50325.2773
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49683.9766 - mae: 49683.9766 - val_loss: 50319.0156 - val_mae: 50319.0156
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49672.6094 - mae: 49672.6094 - val_loss: 50306.1680 - val_mae: 50306.1680
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49658.0352 - mae: 49658.0352 - val_loss: 50296.4414 - val_mae: 50296.4414
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49649.0195 - mae: 49649.0195 - val_loss: 50291.8047 - val_mae: 50291.8047
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49638.7109 - mae: 49638.7109 - val_loss: 50285.1914 - val_mae: 50285.1914
Epoch 37/100
250/250 [==============================] - 1s 5ms/step - loss: 49626.1094 - mae: 49626.1094 - val_loss: 50286.8594 - val_mae: 50286.8594
Epoch 38/100
250/250 [==============================] - 2s 7ms/step - loss: 49619.1523 - mae: 49619.1523 - val_loss: 50275.5117 - val_mae: 50275.5117
Epoch 39/100
250/250 [==============================] - 1s 6ms/step - loss: 49605.3125 - mae: 49605.3125 - val_loss: 50281.2539 - val_mae: 50281.2539
Epoch 40/100
250/250 [==============================] - 1s 5ms/step - loss: 49598.0938 - mae: 49598.0938 - val_loss: 50262.9727 - val_mae: 50262.9727
Epoch 41/100
250/250 [==============================] - 1s 5ms/step - loss: 49594.7070 - mae: 49594.7070 - val_loss: 50264.4062 - val_mae: 50264.4062
Epoch 42/100
250/250 [==============================] - 1s 5ms/step - loss: 49584.2734 - mae: 49584.2734 - val_loss: 50268.5273 - val_mae: 50268.5273
Epoch 43/100
250/250 [==============================] - 1s 5ms/step - loss: 49573.8516 - mae: 49573.8516 - val_loss: 50267.8945 - val_mae: 50267.8945
Epoch 44/100
250/250 [==============================] - 1s 5ms/step - loss: 49568.6172 - mae: 49568.6172 - val_loss: 50262.1953 - val_mae: 50262.1953
Epoch 45/100
250/250 [==============================] - 1s 5ms/step - loss: 49556.6055 - mae: 49556.6055 - val_loss: 50259.6523 - val_mae: 50259.6523
Epoch 46/100
250/250 [==============================] - 1s 6ms/step - loss: 49552.7461 - mae: 49552.7461 - val_loss: 50259.8633 - val_mae: 50259.8633
Epoch 47/100
250/250 [==============================] - 2s 6ms/step - loss: 49544.2852 - mae: 49544.2852 - val_loss: 50283.6367 - val_mae: 50283.6367
Epoch 48/100
250/250 [==============================] - 2s 8ms/step - loss: 49540.1328 - mae: 49540.1328 - val_loss: 50267.0000 - val_mae: 50267.0000
Epoch 49/100
250/250 [==============================] - 2s 8ms/step - loss: 49531.8320 - mae: 49531.8320 - val_loss: 50277.3398 - val_mae: 50277.3398
Epoch 50/100
250/250 [==============================] - 2s 7ms/step - loss: 49524.7812 - mae: 49524.7812 - val_loss: 50272.4961 - val_mae: 50272.4961

In [18]:
%load_ext tensorboard

In [19]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 4148), started 12:03:22 ago. (Use '!kill 4148' to kill it.)

In [20]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 [==============================] - 0s 5ms/step - loss: 50259.6523 - mae: 50259.6523
Test Loss: 50259.65234375, Test MAE: 50259.65234375

In [21]:
model.save('regression_model.h5')

d:\udemy\DL\ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(